//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pen1_website.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pen1_website.Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Systems.
        /// </summary>
        public static string Barcode_Systems {
            get {
                return ResourceManager.GetString("Barcode Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Drop Unit.
        /// </summary>
        public static string Book_Drop_Unit {
            get {
                return ResourceManager.GetString("Book Drop Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash TopUp and Fine Payment Systems.
        /// </summary>
        public static string Cash_TopUp_and_Fine_Payment_Systems {
            get {
                return ResourceManager.GetString("Cash TopUp and Fine Payment Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulation Circuit.
        /// </summary>
        public static string Circulation_Circuit {
            get {
                return ResourceManager.GetString("Circulation Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulation Circuit Programming Station.
        /// </summary>
        public static string Circulation_Circuit_Programming_Station {
            get {
                return ResourceManager.GetString("Circulation Circuit Programming Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electromagnetic Security.
        /// </summary>
        public static string Electromagnetic_Security {
            get {
                return ResourceManager.GetString("Electromagnetic Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate Portal Monitor.
        /// </summary>
        public static string Gate_Portal_Monitor {
            get {
                return ResourceManager.GetString("Gate Portal Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Labeling One-Line.
        /// </summary>
        public static string Hand_Labeling_One_Line {
            get {
                return ResourceManager.GetString("Hand Labeling One-Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Labeling Systems.
        /// </summary>
        public static string Hand_Labeling_Systems {
            get {
                return ResourceManager.GetString("Hand Labeling Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Labeling Two-Line.
        /// </summary>
        public static string Hand_Labeling_Two_Line {
            get {
                return ResourceManager.GetString("Hand Labeling Two-Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handheld Application.
        /// </summary>
        public static string Handheld_Application {
            get {
                return ResourceManager.GetString("Handheld Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS Controller.
        /// </summary>
        public static string ILS_Controller {
            get {
                return ResourceManager.GetString("ILS Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Library System with RFID.
        /// </summary>
        public static string Intelligent_Library_System_with_RFID {
            get {
                return ResourceManager.GetString("Intelligent Library System with RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Sensors Gate.
        /// </summary>
        public static string Intelligent_Sensors_Gate {
            get {
                return ResourceManager.GetString("Intelligent Sensors Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Portable Reader.
        /// </summary>
        public static string Inventory_Portable_Reader {
            get {
                return ResourceManager.GetString("Inventory Portable Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Management Systems.
        /// </summary>
        public static string Library_Management_Systems {
            get {
                return ResourceManager.GetString("Library Management Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        public static string Mercury {
            get {
                return ResourceManager.GetString("Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mifare Reader.
        /// </summary>
        public static string Mifare_Reader {
            get {
                return ResourceManager.GetString("Mifare Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other details.
        /// </summary>
        public static string Other_details {
            get {
                return ResourceManager.GetString("Other details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Sample References.
        /// </summary>
        public static string Our_Sample_References {
            get {
                return ResourceManager.GetString("Our Sample References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patron Self-Checkout.
        /// </summary>
        public static string Patron_Self_Checkout {
            get {
                return ResourceManager.GetString("Patron Self-Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF-EAS Systems.
        /// </summary>
        public static string RF_EAS_Systems {
            get {
                return ResourceManager.GetString("RF-EAS Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Map.
        /// </summary>
        public static string RFID_Map {
            get {
                return ResourceManager.GetString("RFID Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Patron Cards.
        /// </summary>
        public static string RFID_Patron_Cards {
            get {
                return ResourceManager.GetString("RFID Patron Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site map.
        /// </summary>
        public static string Site_map {
            get {
                return ResourceManager.GetString("Site map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Station Reader.
        /// </summary>
        public static string Staff_Station_Reader {
            get {
                return ResourceManager.GetString("Staff Station Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training and system maintenance.
        /// </summary>
        public static string Training_and_system_maintenance {
            get {
                return ResourceManager.GetString("Training and system maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Knowledge.
        /// </summary>
        public static string V_Knowledge {
            get {
                return ResourceManager.GetString("V-Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Management System with RFID.
        /// </summary>
        public static string Warehouse_Management_System_with_RFID {
            get {
                return ResourceManager.GetString("Warehouse Management System with RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application.
        /// </summary>
        public static string Web_Application {
            get {
                return ResourceManager.GetString("Web Application", resourceCulture);
            }
        }
    }
}
